mysql:
  username: "root"
  password: "G_cloud3#qQfPfHP"
  path: "121.37.171.251:3306"
  db-name: "test"
  config: "charset=utf8&parseTime=True&loc=Local"
  max-idle-conns: 20
  max-open-conns: 20
  log-mode: false

redis:
  addr: '121.42.227.165:6379'
  password: 'ZvZg2R8L8rbg9y'
  db: 0

system:
  env: 'public'  # Change to "develop" to skip authentication for development mode
  addr: 8888
  db-type: "mysql"  # support mysql/sqlite

jwt:
  signing-key: "swhcs"
